name: Build, Test, and Publish
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  id-token: write
  pages: write
jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Quickest tests to run
      - name: Unit Tests
        run: npm run jest:ci

      #  Build and test storybook more completely
      - name: Build Storybook
        run: npm run storybook:build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Serve Storybook and Run Smoke and Playwright Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run storybook:test && npm run playwright"

      - name: Upload Storybook Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './storybook-static'

      # Compile Library
      - name: Compile library
        run: npm run build
        if: github.event_name != 'pull_request'

      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-library
          path: |
            dist
            readme.md
            package.json
            LICENSE

  publish:
    timeout-minutes: 20
    needs: build-and-test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Download the Built Artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-library

      - name: Publish Library using Built Artifact
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISHING_TOKEN }}

      # Publish storybook to pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3